import { today } from 'src/utils/format-time';

import { CONFIG } from 'src/config-global';

import { _mock } from './_mock';

// APP
// ----------------------------------------------------------------------

export const _memorizedSurah = [
  {
    id: '1',
    name: 'Al-Fatihah',
    arabicName: 'الفاتحة',
    juz: 1,
    hizb: 1,
    totalVerses: 7,
    totalMemorized: 7,
    totalUnmemorized: 0,
    typeSurah: 'Meccan',
  },
  {
    id: '2',
    name: 'Al-Baqarah',
    arabicName: 'البقرة',
    juz: 1,
    hizb: 1,
    totalVerses: 286,
    totalMemorized: 286,
    totalUnmemorized: 0,
    typeSurah: 'Medinan',
  },
  {
    id: '3',
    name: 'Al-Imran',
    arabicName: 'آل عمران',
    juz: 3,
    hizb: 6,
    totalVerses: 200,
    totalMemorized: 83,
    totalUnmemorized: 117,
    typeSurah: 'Medinan',
  },
  {
    id: '4',
    name: 'An-Nisa',
    arabicName: 'النساء',
    juz: 4,
    hizb: 8,
    totalVerses: 176,
    totalMemorized: 0,
    totalUnmemorized: 176,
    typeSurah: 'Medinan',
  },
  {
    id: '5',
    name: 'Al-Maidah',
    arabicName: 'المائدة',
    juz: 6,
    hizb: 11,
    totalVerses: 120,
    totalMemorized: 0,
    totalUnmemorized: 120,
    typeSurah: 'Medinan',
  },
  {
    id: '6',
    name: 'Al-Anam',
    arabicName: 'الأنعام',
    juz: 8,
    hizb: 15,
    totalVerses: 165,
    totalMemorized: 0,
    totalUnmemorized: 165,
    typeSurah: 'Meccan',
  },
  {
    id: '7',
    name: 'Al-Araf',
    arabicName: 'الأعراف',
    juz: 10,
    hizb: 19,
    totalVerses: 206,
    totalMemorized: 0,
    totalUnmemorized: 206,
    typeSurah: 'Meccan',
  },
  {
    id: '8',
    name: 'Al-Anfal',
    arabicName: 'الأنفال',
    juz: 11,
    hizb: 22,
    totalVerses: 75,
    totalMemorized: 0,
    totalUnmemorized: 75,
    typeSurah: 'Medinan',
  },
  {
    id: '9',
    name: 'At-Tawbah',
    arabicName: 'التوبة',
    juz: 11,
    hizb: 24,
    totalVerses: 129,
    totalMemorized: 0,
    totalUnmemorized: 129,
    typeSurah: 'Medinan',
  },
  {
    id: '10',
    name: 'Yunus',
    arabicName: 'يونس',
    juz: 11,
    hizb: 25,
    totalVerses: 109,
    totalMemorized: 0,
    totalUnmemorized: 109,
    typeSurah: 'Meccan',
  },
  {
    id: '11',
    name: 'Hud',
    arabicName: 'هود',
    juz: 12,
    hizb: 27,
    totalVerses: 123,
    totalMemorized: 0,
    totalUnmemorized: 123,
    typeSurah: 'Meccan',
  },
  {
    id: '12',
    name: 'Yusuf',
    arabicName: 'يوسف',
    juz: 12,
    hizb: 29,
    totalVerses: 111,
    totalMemorized: 0,
    totalUnmemorized: 111,
    typeSurah: 'Meccan',
  },
  {
    id: '13',
    name: 'Ar-Rad',
    arabicName: 'الرعد',
    juz: 13,
    hizb: 31,
    totalVerses: 43,
    totalMemorized: 0,
    totalUnmemorized: 43,
    typeSurah: 'Medinan',
  },
  {
    id: '14',
    name: 'Ibrahim',
    arabicName: 'إبراهيم',
    juz: 13,
    hizb: 32,
    totalVerses: 52,
    totalMemorized: 0,
    totalUnmemorized: 52,
    typeSurah: 'Meccan',
  },
  {
    id: '15',
    name: 'Al-Hijr',
    arabicName: 'الحجر',
    juz: 14,
    hizb: 34,
    totalVerses: 99,
    totalMemorized: 0,
    totalUnmemorized: 99,
    typeSurah: 'Meccan',
  },
  {
    id: '16',
    name: 'An-Nahl',
    arabicName: 'النحل',
    juz: 14,
    hizb: 36,
    totalVerses: 128,
    totalMemorized: 0,
    totalUnmemorized: 128,
    typeSurah: 'Meccan',
  },
  {
    id: '17',
    name: 'Al-Isra',
    arabicName: 'الإسراء',
    juz: 15,
    hizb: 38,
    totalVerses: 111,
    totalMemorized: 0,
    totalUnmemorized: 111,
    typeSurah: 'Meccan',
  },
  {
    id: '18',
    name: 'Al-Kahf',
    arabicName: 'الكهف',
    juz: 15,
    hizb: 40,
    totalVerses: 110,
    totalMemorized: 0,
    totalUnmemorized: 110,
    typeSurah: 'Meccan',
  },
  {
    id: '19',
    name: 'Maryam',
    arabicName: 'مريم',
    juz: 16,
    hizb: 42,
    totalVerses: 98,
    totalMemorized: 0,
    totalUnmemorized: 98,
    typeSurah: 'Meccan',
  },
  {
    id: '20',
    name: 'Ta-Ha',
    arabicName: 'طه',
    juz: 16,
    hizb: 44,
    totalVerses: 135,
    totalMemorized: 0,
    totalUnmemorized: 135,
    typeSurah: 'Meccan',
  },
  {
    id: '21',
    name: 'Al-Anbiya',
    arabicName: 'الأنبياء',
    juz: 17,
    hizb: 46,
    totalVerses: 112,
    totalMemorized: 0,
    totalUnmemorized: 112,
    typeSurah: 'Meccan',
  },
  {
    id: '22',
    name: 'Al-Hajj',
    arabicName: 'الحج',
    juz: 18,
    hizb: 48,
    totalVerses: 78,
    totalMemorized: 0,
    totalUnmemorized: 78,
    typeSurah: 'Meccan',
  },
  {
    id: '23',
    name: 'Al-Muminun',
    arabicName: 'المؤمنون',
    juz: 18,
    hizb: 51,
    totalVerses: 118,
    totalMemorized: 0,
    totalUnmemorized: 118,
    typeSurah: 'Meccan',
  },
  {
    id: '24',
    name: 'An-Nur',
    arabicName: 'النور',
    juz: 18,
    hizb: 53,
    totalVerses: 64,
    totalMemorized: 0,
    totalUnmemorized: 64,
    typeSurah: 'Medinan',
  },
  {
    id: '25',
    name: 'Al-Furqan',
    arabicName: 'الفرقان',
    juz: 19,
    hizb: 55,
    totalVerses: 77,
    totalMemorized: 0,
    totalUnmemorized: 77,
    typeSurah: 'Meccan',
  },
  {
    id: '26',
    name: 'Ash-Shuara',
    arabicName: 'الشعراء',
    juz: 19,
    hizb: 57,
    totalVerses: 227,
    totalMemorized: 0,
    totalUnmemorized: 227,
    typeSurah: 'Meccan',
  },
  {
    id: '27',
    name: 'An-Naml',
    arabicName: 'النمل',
    juz: 20,
    hizb: 59,
    totalVerses: 93,
    totalMemorized: 0,
    totalUnmemorized: 93,
    typeSurah: 'Meccan',
  },
  {
    id: '28',
    name: 'Al-Qasas',
    arabicName: 'القصص',
    juz: 20,
    hizb: 61,
    totalVerses: 88,
    totalMemorized: 0,
    totalUnmemorized: 88,
    typeSurah: 'Meccan',
  },
  {
    id: '29',
    name: 'Al-Ankabut',
    arabicName: 'العنكبوت',
    juz: 21,
    hizb: 63,
    totalVerses: 69,
    totalMemorized: 0,
    totalUnmemorized: 69,
    typeSurah: 'Meccan',
  },
  {
    id: '30',
    name: 'Ar-Rum',
    arabicName: 'الروم',
    juz: 21,
    hizb: 65,
    totalVerses: 60,
    totalMemorized: 0,
    totalUnmemorized: 60,
    typeSurah: 'Meccan',
  },
  {
    id: '31',
    name: 'Luqman',
    arabicName: 'لقمان',
    juz: 21,
    hizb: 67,
    totalVerses: 34,
    totalMemorized: 0,
    totalUnmemorized: 34,
    typeSurah: 'Meccan',
  },
  {
    id: '32',
    name: 'As-Sajda',
    arabicName: 'السجدة',
    juz: 22,
    hizb: 69,
    totalVerses: 30,
    totalMemorized: 0,
    totalUnmemorized: 30,
    typeSurah: 'Meccan',
  },
  {
    id: '33',
    name: 'Al-Ahzab',
    arabicName: 'الأحزاب',
    juz: 22,
    hizb: 71,
    totalVerses: 73,
    totalMemorized: 0,
    totalUnmemorized: 73,
    typeSurah: 'Medinan',
  },
  {
    id: '34',
    name: 'Saba',
    arabicName: 'سبأ',
    juz: 23,
    hizb: 73,
    totalVerses: 54,
    totalMemorized: 0,
    totalUnmemorized: 54,
    typeSurah: 'Meccan',
  },
  {
    id: '35',
    name: 'Fatir',
    arabicName: 'فاطر',
    juz: 23,
    hizb: 75,
    totalVerses: 45,
    totalMemorized: 0,
    totalUnmemorized: 45,
    typeSurah: 'Meccan',
  },
  {
    id: '36',
    name: 'Ya-Sin',
    arabicName: 'يس',
    juz: 23,
    hizb: 77,
    totalVerses: 83,
    totalMemorized: 0,
    totalUnmemorized: 83,
    typeSurah: 'Meccan',
  },
  {
    id: '37',
    name: 'As-Saffat',
    arabicName: 'الصافات',
    juz: 24,
    hizb: 79,
    totalVerses: 182,
    totalMemorized: 0,
    totalUnmemorized: 182,
    typeSurah: 'Meccan',
  },
  {
    id: '38',
    name: 'Sad',
    arabicName: 'ص',
    juz: 24,
    hizb: 81,
    totalVerses: 88,
    totalMemorized: 0,
    totalUnmemorized: 88,
    typeSurah: 'Meccan',
  },
  {
    id: '39',
    name: 'Az-Zumar',
    arabicName: 'الزمر',
    juz: 24,
    hizb: 83,
    totalVerses: 75,
    totalMemorized: 0,
    totalUnmemorized: 75,
    typeSurah: 'Meccan',
  },
  {
    id: '40',
    name: 'Ghafir',
    arabicName: 'غافر',
    juz: 25,
    hizb: 85,
    totalVerses: 85,
    totalMemorized: 0,
    totalUnmemorized: 85,
    typeSurah: 'Meccan',
  },
  {
    id: '41',
    name: 'Fussilat',
    arabicName: 'فصلت',
    juz: 25,
    hizb: 87,
    totalVerses: 54,
    totalMemorized: 0,
    totalUnmemorized: 54,
    typeSurah: 'Meccan',
  },
  {
    id: '42',
    name: 'Ash-Shura',
    arabicName: 'الشورى',
    juz: 25,
    hizb: 89,
    totalVerses: 53,
    totalMemorized: 0,
    totalUnmemorized: 53,
    typeSurah: 'Meccan',
  },
  {
    id: '43',
    name: 'Az-Zukhruf',
    arabicName: 'الزخرف',
    juz: 25,
    hizb: 91,
    totalVerses: 89,
    totalMemorized: 0,
    totalUnmemorized: 89,
    typeSurah: 'Meccan',
  },
  {
    id: '44',
    name: 'Ad-Dukhan',
    arabicName: 'الدخان',
    juz: 26,
    hizb: 93,
    totalVerses: 59,
    totalMemorized: 0,
    totalUnmemorized: 59,
    typeSurah: 'Meccan',
  },
  {
    id: '45',
    name: 'Al-Jathiya',
    arabicName: 'الجاثية',
    juz: 26,
    hizb: 95,
    totalVerses: 37,
    totalMemorized: 0,
    totalUnmemorized: 37,
    typeSurah: 'Meccan',
  },
  {
    id: '46',
    name: 'Al-Ahqaf',
    arabicName: 'الأحقاف',
    juz: 26,
    hizb: 97,
    totalVerses: 35,
    totalMemorized: 0,
    totalUnmemorized: 35,
    typeSurah: 'Meccan',
  },
  {
    id: '47',
    name: 'Muhammad',
    arabicName: 'محمد',
    juz: 26,
    hizb: 99,
    totalVerses: 38,
    totalMemorized: 0,
    totalUnmemorized: 38,
    typeSurah: 'Medinan',
  },
  {
    id: '48',
    name: 'Al-Fath',
    arabicName: 'الفتح',
    juz: 26,
    hizb: 101,
    totalVerses: 29,
    totalMemorized: 0,
    totalUnmemorized: 29,
    typeSurah: 'Medinan',
  },
  {
    id: '49',
    name: 'Al-Hujraat',
    arabicName: 'الحجرات',
    juz: 26,
    hizb: 103,
    totalVerses: 18,
    totalMemorized: 0,
    totalUnmemorized: 18,
    typeSurah: 'Medinan',
  },
  {
    id: '50',
    name: 'Qaf',
    arabicName: 'ق',
    juz: 26,
    hizb: 105,
    totalVerses: 45,
    totalMemorized: 0,
    totalUnmemorized: 45,
    typeSurah: 'Meccan',
  },
  {
    id: '51',
    name: 'Adh-Dhariyat',
    arabicName: 'الذاريات',
    juz: 27,
    hizb: 107,
    totalVerses: 60,
    totalMemorized: 0,
    totalUnmemorized: 60,
    typeSurah: 'Meccan',
  },
  {
    id: '52',
    name: 'At-Tur',
    arabicName: 'الطور',
    juz: 27,
    hizb: 109,
    totalVerses: 49,
    totalMemorized: 0,
    totalUnmemorized: 49,
    typeSurah: 'Meccan',
  },
  {
    id: '53',
    name: 'An-Najm',
    arabicName: 'النجم',
    juz: 27,
    hizb: 111,
    totalVerses: 62,
    totalMemorized: 0,
    totalUnmemorized: 62,
    typeSurah: 'Meccan',
  },
  {
    id: '54',
    name: 'Al-Qamar',
    arabicName: 'القمر',
    juz: 27,
    hizb: 113,
    totalVerses: 55,
    totalMemorized: 0,
    totalUnmemorized: 55,
    typeSurah: 'Meccan',
  },
  {
    id: '55',
    name: 'Ar-Rahman',
    arabicName: 'الرحمن',
    juz: 27,
    hizb: 115,
    totalVerses: 78,
    totalMemorized: 0,
    totalUnmemorized: 78,
    typeSurah: 'Medinan',
  },
  {
    id: '56',
    name: 'Al-Waqia',
    arabicName: 'الواقعة',
    juz: 28,
    hizb: 117,
    totalVerses: 96,
    totalMemorized: 0,
    totalUnmemorized: 96,
    typeSurah: 'Meccan',
  },
  {
    id: '57',
    name: 'Al-Hadid',
    arabicName: 'الحديد',
    juz: 28,
    hizb: 119,
    totalVerses: 29,
    totalMemorized: 0,
    totalUnmemorized: 29,
    typeSurah: 'Medinan',
  },
  {
    id: '58',
    name: 'Al-Mujadila',
    arabicName: 'المجادلة',
    juz: 28,
    hizb: 121,
    totalVerses: 22,
    totalMemorized: 0,
    totalUnmemorized: 22,
    typeSurah: 'Medinan',
  },
  {
    id: '59',
    name: 'Al-Hashr',
    arabicName: 'الحشر',
    juz: 28,
    hizb: 123,
    totalVerses: 24,
    totalMemorized: 0,
    totalUnmemorized: 24,
    typeSurah: 'Medinan',
  },
  {
    id: '60',
    name: 'Al-Mumtahina',
    arabicName: 'الممتحنة',
    juz: 28,
    hizb: 125,
    totalVerses: 13,
    totalMemorized: 0,
    totalUnmemorized: 13,
    typeSurah: 'Medinan',
  },
  {
    id: '61',
    name: 'As-Saff',
    arabicName: 'الصف',
    juz: 28,
    hizb: 127,
    totalVerses: 14,
    totalMemorized: 0,
    totalUnmemorized: 14,
    typeSurah: 'Medinan',
  },
  {
    id: '62',
    name: 'Al-Jumua',
    arabicName: 'الجمعة',
    juz: 28,
    hizb: 129,
    totalVerses: 11,
    totalMemorized: 0,
    totalUnmemorized: 11,
    typeSurah: 'Medinan',
  },
  {
    id: '63',
    name: 'Al-Munafiqoon',
    arabicName: 'المنافقون',
    juz: 28,
    hizb: 131,
    totalVerses: 11,
    totalMemorized: 0,
    totalUnmemorized: 11,
    typeSurah: 'Medinan',
  },
  {
    id: '64',
    name: 'At-Taghabun',
    arabicName: 'التغابن',
    juz: 28,
    hizb: 133,
    totalVerses: 18,
    totalMemorized: 0,
    totalUnmemorized: 18,
    typeSurah: 'Medinan',
  },
  {
    id: '65',
    name: 'At-Talaq',
    arabicName: 'الطلاق',
    juz: 28,
    hizb: 135,
    totalVerses: 12,
    totalMemorized: 0,
    totalUnmemorized: 12,
    typeSurah: 'Medinan',
  },
  {
    id: '66',
    name: 'At-Tahrim',
    arabicName: 'التحريم',
    juz: 28,
    hizb: 137,
    totalVerses: 12,
    totalMemorized: 0,
    totalUnmemorized: 12,
    typeSurah: 'Medinan',
  },
  {
    id: '67',
    name: 'Al-Mulk',
    arabicName: 'الملك',
    juz: 29,
    hizb: 139,
    totalVerses: 30,
    totalMemorized: 0,
    totalUnmemorized: 30,
    typeSurah: 'Meccan',
  },
  {
    id: '68',
    name: 'Al-Qalam',
    arabicName: 'القلم',
    juz: 29,
    hizb: 141,
    totalVerses: 52,
    totalMemorized: 0,
    totalUnmemorized: 52,
    typeSurah: 'Meccan',
  },
  {
    id: '69',
    name: 'Al-Haaqqa',
    arabicName: 'الحاقة',
    juz: 29,
    hizb: 143,
    totalVerses: 52,
    totalMemorized: 0,
    totalUnmemorized: 52,
    typeSurah: 'Meccan',
  },
  {
    id: '70',
    name: 'Al-Maarij',
    arabicName: 'المعارج',
    juz: 29,
    hizb: 145,
    totalVerses: 44,
    totalMemorized: 0,
    totalUnmemorized: 44,
    typeSurah: 'Meccan',
  },
  {
    id: '71',
    name: 'Nuh',
    arabicName: 'نوح',
    juz: 29,
    hizb: 147,
    totalVerses: 28,
    totalMemorized: 0,
    totalUnmemorized: 28,
    typeSurah: 'Meccan',
  },
  {
    id: '72',
    name: 'Al-Jinn',
    arabicName: 'الجن',
    juz: 29,
    hizb: 149,
    totalVerses: 28,
    totalMemorized: 0,
    totalUnmemorized: 28,
    typeSurah: 'Meccan',
  },
  {
    id: '73',
    name: 'Al-Muzzammil',
    arabicName: 'المزمل',
    juz: 29,
    hizb: 151,
    totalVerses: 20,
    totalMemorized: 0,
    totalUnmemorized: 20,
    typeSurah: 'Meccan',
  },
  {
    id: '74',
    name: 'Al-Muddathir',
    arabicName: 'المدثر',
    juz: 29,
    hizb: 153,
    totalVerses: 56,
    totalMemorized: 0,
    totalUnmemorized: 56,
    typeSurah: 'Meccan',
  },
  {
    id: '75',
    name: 'Al-Qiyama',
    arabicName: 'القيامة',
    juz: 29,
    hizb: 155,
    totalVerses: 40,
    totalMemorized: 0,
    totalUnmemorized: 40,
    typeSurah: 'Meccan',
  },
  {
    id: '76',
    name: 'Al-Insan',
    arabicName: 'الإنسان',
    juz: 29,
    hizb: 157,
    totalVerses: 31,
    totalMemorized: 0,
    totalUnmemorized: 31,
    typeSurah: 'Medinan',
  },
  {
    id: '77',
    name: 'Al-Mursalat',
    arabicName: 'المرسلات',
    juz: 29,
    hizb: 159,
    totalVerses: 50,
    totalMemorized: 0,
    totalUnmemorized: 50,
    typeSurah: 'Meccan',
  },
  {
    id: '78',
    name: 'An-Naba',
    arabicName: 'النبأ',
    juz: 30,
    hizb: 161,
    totalVerses: 40,
    totalMemorized: 0,
    totalUnmemorized: 40,
    typeSurah: 'Meccan',
  },
  {
    id: '79',
    name: 'An-Naziat',
    arabicName: 'النازعات',
    juz: 30,
    hizb: 163,
    totalVerses: 46,
    totalMemorized: 0,
    totalUnmemorized: 46,
    typeSurah: 'Meccan',
  },
  {
    id: '80',
    name: 'Abasa',
    arabicName: 'عبس',
    juz: 30,
    hizb: 165,
    totalVerses: 42,
    totalMemorized: 0,
    totalUnmemorized: 42,
    typeSurah: 'Meccan',
  },
  {
    id: '81',
    name: 'At-Takwir',
    arabicName: 'التكوير',
    juz: 30,
    hizb: 167,
    totalVerses: 29,
    totalMemorized: 0,
    totalUnmemorized: 29,
    typeSurah: 'Meccan',
  },
  {
    id: '82',
    name: 'Al-Infitar',
    arabicName: 'الإنفطار',
    juz: 30,
    hizb: 169,
    totalVerses: 19,
    totalMemorized: 0,
    totalUnmemorized: 19,
    typeSurah: 'Meccan',
  },
  {
    id: '83',
    name: 'Al-Mutaffifin',
    arabicName: 'المطففين',
    juz: 30,
    hizb: 171,
    totalVerses: 36,
    totalMemorized: 0,
    totalUnmemorized: 36,
    typeSurah: 'Meccan',
  },
  {
    id: '84',
    name: 'Al-Inshiqaq',
    arabicName: 'الإنشقاق',
    juz: 30,
    hizb: 173,
    totalVerses: 25,
    totalMemorized: 0,
    totalUnmemorized: 25,
    typeSurah: 'Meccan',
  },
  {
    id: '85',
    name: 'Al-Burooj',
    arabicName: 'البروج',
    juz: 30,
    hizb: 175,
    totalVerses: 22,
    totalMemorized: 0,
    totalUnmemorized: 22,
    typeSurah: 'Meccan',
  },
  {
    id: '86',
    name: 'At-Tariq',
    arabicName: 'الطارق',
    juz: 30,
    hizb: 177,
    totalVerses: 17,
    totalMemorized: 0,
    totalUnmemorized: 17,
    typeSurah: 'Meccan',
  },
  {
    id: '87',
    name: 'Al-Ala',
    arabicName: 'الأعلى',
    juz: 30,
    hizb: 179,
    totalVerses: 19,
    totalMemorized: 0,
    totalUnmemorized: 19,
    typeSurah: 'Meccan',
  },
  {
    id: '88',
    name: 'Al-Ghashiya',
    arabicName: 'الغاشية',
    juz: 30,
    hizb: 181,
    totalVerses: 26,
    totalMemorized: 0,
    totalUnmemorized: 26,
    typeSurah: 'Meccan',
  },
  {
    id: '89',
    name: 'Al-Fajr',
    arabicName: 'الفجر',
    juz: 30,
    hizb: 183,
    totalVerses: 30,
    totalMemorized: 0,
    totalUnmemorized: 30,
    typeSurah: 'Meccan',
  },
  {
    id: '90',
    name: 'Al-Balad',
    arabicName: 'البلد',
    juz: 30,
    hizb: 185,
    totalVerses: 20,
    totalMemorized: 0,
    totalUnmemorized: 20,
    typeSurah: 'Meccan',
  },
  {
    id: '91',
    name: 'Ash-Shams',
    arabicName: 'الشمس',
    juz: 30,
    hizb: 187,
    totalVerses: 15,
    totalMemorized: 0,
    totalUnmemorized: 15,
    typeSurah: 'Meccan',
  },
  {
    id: '92',
    name: 'Al-Lail',
    arabicName: 'الليل',
    juz: 30,
    hizb: 189,
    totalVerses: 21,
    totalMemorized: 0,
    totalUnmemorized: 21,
    typeSurah: 'Meccan',
  },
  {
    id: '93',
    name: 'Ad-Duhaa',
    arabicName: 'الضحى',
    juz: 30,
    hizb: 191,
    totalVerses: 11,
    totalMemorized: 0,
    totalUnmemorized: 11,
    typeSurah: 'Meccan',
  },
  {
    id: '94',
    name: 'Ash-Sharh',
    arabicName: 'الشرح',
    juz: 30,
    hizb: 193,
    totalVerses: 8,
    totalMemorized: 0,
    totalUnmemorized: 8,
    typeSurah: 'Meccan',
  },
  {
    id: '95',
    name: 'At-Tin',
    arabicName: 'التين',
    juz: 30,
    hizb: 195,
    totalVerses: 8,
    totalMemorized: 0,
    totalUnmemorized: 8,
    typeSurah: 'Meccan',
  },
  {
    id: '96',
    name: 'Al-Alaq',
    arabicName: 'العلق',
    juz: 30,
    hizb: 197,
    totalVerses: 19,
    totalMemorized: 0,
    totalUnmemorized: 19,
    typeSurah: 'Meccan',
  },
  {
    id: '97',
    name: 'Al-Qadr',
    arabicName: 'القدر',
    juz: 30,
    hizb: 199,
    totalVerses: 5,
    totalMemorized: 0,
    totalUnmemorized: 5,
    typeSurah: 'Meccan',
  },
  {
    id: '98',
    name: 'Al-Bayyina',
    arabicName: 'البينة',
    juz: 30,
    hizb: 201,
    totalVerses: 8,
    totalMemorized: 0,
    totalUnmemorized: 8,
    typeSurah: 'Medinan',
  },
  {
    id: '99',
    name: 'Az-Zalzala',
    arabicName: 'الزلزلة',
    juz: 30,
    hizb: 203,
    totalVerses: 8,
    totalMemorized: 0,
    totalUnmemorized: 8,
    typeSurah: 'Medinan',
  },
  {
    id: '100',
    name: 'Al-Adiyat',
    arabicName: 'العاديات',
    juz: 30,
    hizb: 205,
    totalVerses: 11,
    totalMemorized: 0,
    totalUnmemorized: 11,
    typeSurah: 'Meccan',
  },
  {
    id: '101',
    name: 'Al-Qaria',
    arabicName: 'القارعة',
    juz: 30,
    hizb: 207,
    totalVerses: 11,
    totalMemorized: 0,
    totalUnmemorized: 11,
    typeSurah: 'Meccan',
  },
  {
    id: '102',
    name: 'At-Takathur',
    arabicName: 'التكاثر',
    juz: 30,
    hizb: 209,
    totalVerses: 8,
    totalMemorized: 0,
    totalUnmemorized: 8,
    typeSurah: 'Meccan',
  },
  {
    id: '103',
    name: 'Al-Asr',
    arabicName: 'العصر',
    juz: 30,
    hizb: 211,
    totalVerses: 3,
    totalMemorized: 0,
    totalUnmemorized: 3,
    typeSurah: 'Meccan',
  },
  {
    id: '104',
    name: 'Al-Humaza',
    arabicName: 'الهمزة',
    juz: 30,
    hizb: 213,
    totalVerses: 9,
    totalMemorized: 0,
    totalUnmemorized: 9,
    typeSurah: 'Meccan',
  },
  {
    id: '105',
    name: 'Al-Fil',
    arabicName: 'الفيل',
    juz: 30,
    hizb: 215,
    totalVerses: 5,
    totalMemorized: 0,
    totalUnmemorized: 5,
    typeSurah: 'Meccan',
  },
  {
    id: '106',
    name: 'Quraish',
    arabicName: 'قريش',
    juz: 30,
    hizb: 217,
    totalVerses: 4,
    totalMemorized: 0,
    totalUnmemorized: 4,
    typeSurah: 'Meccan',
  },
  {
    id: '107',
    name: 'Al-Maun',
    arabicName: 'الماعون',
    juz: 30,
    hizb: 219,
    totalVerses: 7,
    totalMemorized: 0,
    totalUnmemorized: 7,
    typeSurah: 'Meccan',
  },
  {
    id: '108',
    name: 'Al-Kawthar',
    arabicName: 'الكوثر',
    juz: 30,
    hizb: 221,
    totalVerses: 3,
    totalMemorized: 0,
    totalUnmemorized: 3,
    typeSurah: 'Meccan',
  },
  {
    id: '109',
    name: 'Al-Kafirun',
    arabicName: 'الكافرون',
    juz: 30,
    hizb: 223,
    totalVerses: 6,
    totalMemorized: 0,
    totalUnmemorized: 6,
    typeSurah: 'Meccan',
  },
  {
    id: '110',
    name: 'An-Nasr',
    arabicName: 'النصر',
    juz: 30,
    hizb: 225,
    totalVerses: 3,
    totalMemorized: 0,
    totalUnmemorized: 3,
    typeSurah: 'Medinan',
  },
  {
    id: '111',
    name: 'Al-Masad',
    arabicName: 'المسد',
    juz: 30,
    hizb: 227,
    totalVerses: 5,
    totalMemorized: 0,
    totalUnmemorized: 5,
    typeSurah: 'Meccan',
  },
  {
    id: '112',
    name: 'Al-Ikhlas',
    arabicName: 'الإخلاص',
    juz: 30,
    hizb: 229,
    totalVerses: 4,
    totalMemorized: 4,
    totalUnmemorized: 0,
    typeSurah: 'Meccan',
  },
  {
    id: '113',
    name: 'Al-Falaq',
    arabicName: 'الفلق',
    juz: 30,
    hizb: 231,
    totalVerses: 5,
    totalMemorized: 5,
    totalUnmemorized: 0,
    typeSurah: 'Meccan',
  },
  {
    id: '114',
    name: 'An-Nas',
    arabicName: 'الناس',
    juz: 30,
    hizb: 233,
    totalVerses: 6,
    totalMemorized: 6,
    totalUnmemorized: 0,
    typeSurah: 'Meccan',
  },
];

export const _appRelated = [
  'Microsoft office 365',
  'Opera',
  'Adobe acrobat reader DC',
  'Joplin',
  'Topaz photo AI',
].map((name, index) => ({
  id: _mock.id(index),
  name,
  downloaded: _mock.number.nativeL(index),
  ratingNumber: _mock.number.rating(index),
  size: _mock.number.nativeL(index) * 1024,
  totalReviews: _mock.number.nativeL(index),
  shortcut: `${CONFIG.assetsDir}/assets/icons/apps/ic-app-${index + 1}.webp`,
  price: [2, 4].includes(index) ? _mock.number.price(index) : 0,
}));

export const _appInstalled = ['Germany', 'England', 'France', 'Korean', 'USA'].map(
  (country, index) => ({
    id: _mock.id(index),
    countryName: country,
    android: _mock.number.nativeL(index),
    windows: _mock.number.nativeL(index + 1),
    apple: _mock.number.nativeL(index + 2),
    countryCode: ['de', 'gb', 'fr', 'kr', 'us'][index],
  })
);

export const _appAuthors = [...Array(3)].map((_, index) => ({
  id: _mock.id(index),
  name: _mock.fullName(index),
  avatarUrl: _mock.image.avatar(index),
  totalFavorites: _mock.number.nativeL(index),
}));

export const _appInvoices = [...Array(5)].map((_, index) => {
  const category = ['Android', 'Mac', 'Windows', 'Android', 'Mac'][index];

  const status = ['paid', 'out of date', 'progress', 'paid', 'paid'][index];

  return {
    id: _mock.id(index),
    invoiceNumber: `INV-199${index}`,
    price: _mock.number.price(index),
    category,
    status,
  };
});

export const _appFeatured = [...Array(3)].map((_, index) => ({
  id: _mock.id(index + 3),
  title: _mock.postTitle(index + 3),
  description: _mock.sentence(index + 3),
  coverUrl: _mock.image.cover(index + 3),
}));

// ANALYTIC
// ----------------------------------------------------------------------

export const _analyticTasks = [...Array(5)].map((_, index) => ({
  id: _mock.id(index),
  name: _mock.taskNames(index),
}));

export const _analyticPosts = [...Array(5)].map((_, index) => ({
  id: _mock.id(index),
  postedAt: _mock.time(index),
  title: _mock.postTitle(index),
  coverUrl: _mock.image.cover(index),
  description: _mock.sentence(index),
}));

export const _analyticOrderTimeline = [...Array(5)].map((_, index) => {
  const title = [
    '1983, orders, $4220',
    '12 Invoices have been paid',
    'Order #37745 from September',
    'New order placed #XF-2356',
    'New order placed #XF-2346',
  ][index];

  return {
    id: _mock.id(index),
    title,
    type: `order${index + 1}`,
    time: _mock.time(index),
  };
});

export const _analyticTraffic = [
  {
    value: 'facebook',
    label: 'Facebook',
    total: _mock.number.nativeL(1),
  },
  {
    value: 'google',
    label: 'Google',
    total: _mock.number.nativeL(2),
  },
  {
    value: 'linkedin',
    label: 'Linkedin',
    total: _mock.number.nativeL(3),
  },
  {
    value: 'twitter',
    label: 'Twitter',
    total: _mock.number.nativeL(4),
  },
];

// ECOMMERCE
// ----------------------------------------------------------------------

export const _ecommerceSalesOverview = ['Total profit', 'Total income', 'Total expenses'].map(
  (label, index) => ({
    label,
    totalAmount: _mock.number.price(index) * 100,
    value: _mock.number.percent(index),
  })
);

export const _ecommerceBestSalesman = [...Array(5)].map((_, index) => {
  const category = ['CAP', 'Branded shoes', 'Headphone', 'Cell phone', 'Earings'][index];

  return {
    id: _mock.id(index),
    category,
    rank: `Top ${index + 1}`,
    email: _mock.email(index),
    name: _mock.fullName(index),
    totalAmount: _mock.number.price(index),
    avatarUrl: _mock.image.avatar(index + 8),
    countryCode: ['de', 'gb', 'fr', 'kr', 'us'][index],
  };
});

export const _ecommerceLatestProducts = [...Array(5)].map((_, index) => {
  const colors = (index === 0 && ['#2EC4B6', '#E71D36', '#FF9F1C', '#011627']) ||
    (index === 1 && ['#92140C', '#FFCF99']) ||
    (index === 2 && ['#0CECDD', '#FFF338', '#FF67E7', '#C400FF', '#52006A', '#046582']) ||
    (index === 3 && ['#845EC2', '#E4007C', '#2A1A5E']) || ['#090088'];

  return {
    id: _mock.id(index),
    colors,
    name: _mock.productName(index),
    price: _mock.number.price(index),
    coverUrl: _mock.image.product(index),
    priceSale: [1, 3].includes(index) ? _mock.number.price(index) : 0,
  };
});

export const _ecommerceNewProducts = [...Array(4)].map((_, index) => ({
  id: _mock.id(index),
  name: _mock.productName(index),
  coverUrl: _mock.image.product(index),
}));

// BANKING
// ----------------------------------------------------------------------

export const _bankingContacts = [...Array(12)].map((_, index) => ({
  id: _mock.id(index),
  name: _mock.fullName(index),
  email: _mock.email(index),
  avatarUrl: _mock.image.avatar(index),
}));

export const _bankingCreditCard = [
  {
    id: _mock.id(2),
    balance: 23432.03,
    cardType: 'mastercard',
    cardHolder: _mock.fullName(2),
    cardNumber: '**** **** **** 3640',
    cardValid: '11/22',
  },
  {
    id: _mock.id(3),
    balance: 18000.23,
    cardType: 'visa',
    cardHolder: _mock.fullName(3),
    cardNumber: '**** **** **** 8864',
    cardValid: '11/25',
  },
  {
    id: _mock.id(4),
    balance: 2000.89,
    cardType: 'mastercard',
    cardHolder: _mock.fullName(4),
    cardNumber: '**** **** **** 7755',
    cardValid: '11/22',
  },
];

export const _bankingRecentTransitions = [
  {
    id: _mock.id(2),
    name: _mock.fullName(2),
    avatarUrl: _mock.image.avatar(2),
    type: 'Income',
    message: 'Receive money from',
    category: 'Annette black',
    date: _mock.time(2),
    status: 'progress',
    amount: _mock.number.price(2),
  },
  {
    id: _mock.id(3),
    name: _mock.fullName(3),
    avatarUrl: _mock.image.avatar(3),
    type: 'Expenses',
    message: 'Payment for',
    category: 'Courtney henry',
    date: _mock.time(3),
    status: 'completed',
    amount: _mock.number.price(3),
  },
  {
    id: _mock.id(4),
    name: _mock.fullName(4),
    avatarUrl: _mock.image.avatar(4),
    type: 'Receive',
    message: 'Payment for',
    category: 'Theresa webb',
    date: _mock.time(4),
    status: 'failed',
    amount: _mock.number.price(4),
  },
  {
    id: _mock.id(5),
    name: null,
    avatarUrl: null,
    type: 'Expenses',
    message: 'Payment for',
    category: 'Fast food',
    date: _mock.time(5),
    status: 'completed',
    amount: _mock.number.price(5),
  },
  {
    id: _mock.id(6),
    name: null,
    avatarUrl: null,
    type: 'Expenses',
    message: 'Payment for',
    category: 'Fitness',
    date: _mock.time(6),
    status: 'progress',
    amount: _mock.number.price(6),
  },
];

// BOOKING
// ----------------------------------------------------------------------

export const _bookings = [...Array(5)].map((_, index) => {
  const status = ['Paid', 'Paid', 'Pending', 'Cancelled', 'Paid'][index];

  const customer = {
    avatarUrl: _mock.image.avatar(index),
    name: _mock.fullName(index),
    phoneNumber: _mock.phoneNumber(index),
  };

  const destination = [...Array(5)].map((__, _index) => ({
    name: _mock.tourName(_index + 1),
    coverUrl: _mock.image.travel(_index + 1),
  }))[index];

  return {
    id: _mock.id(index),
    destination,
    status,
    customer,
    checkIn: _mock.time(index),
    checkOut: _mock.time(index),
  };
});

export const _bookingsOverview = [...Array(3)].map((_, index) => ({
  status: ['Pending', 'Canceled', 'Sold'][index],
  quantity: _mock.number.nativeL(index),
  value: _mock.number.percent(index + 5),
}));

export const _bookingReview = [...Array(5)].map((_, index) => ({
  id: _mock.id(index),
  name: _mock.fullName(index),
  postedAt: _mock.time(index),
  rating: _mock.number.rating(index),
  avatarUrl: _mock.image.avatar(index),
  description: _mock.description(index),
  tags: ['Great sevice', 'Recommended', 'Best price'],
}));

export const _bookingNew = [...Array(8)].map((_, index) => ({
  guests: '3-5',
  id: _mock.id(index),
  bookedAt: _mock.time(index),
  duration: '3 days 2 nights',
  isHot: _mock.boolean(index),
  name: _mock.fullName(index),
  price: _mock.number.price(index),
  avatarUrl: _mock.image.avatar(index),
  coverUrl: _mock.image.travel(index),
}));

// COURSE
// ----------------------------------------------------------------------

export const _coursesContinue = [...Array(4)].map((_, index) => ({
  id: _mock.id(index),
  title: _mock.courseNames(index),
  coverUrl: _mock.image.course(index),
  totalLesson: 12,
  currentLesson: index + 7,
}));

export const _coursesFeatured = [...Array(6)].map((_, index) => ({
  id: _mock.id(index),
  title: _mock.courseNames(index),
  coverUrl: _mock.image.course(index + 6),
  totalDuration: 220,
  totalStudents: _mock.number.nativeM(index),
  price: _mock.number.price(index),
}));

export const _coursesReminder = [...Array(4)].map((_, index) => ({
  id: _mock.id(index),
  title: _mock.courseNames(index),
  totalLesson: 12,
  reminderAt: today(),
  currentLesson: index + 7,
}));
